# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.resize(570, 351)
        AdminWindow.setMinimumSize(QtCore.QSize(570, 319))
        AdminWindow.setMaximumSize(QtCore.QSize(570, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main/Main/Toma4025-Tea-Tea-plant-leaf.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AdminWindow.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(AdminWindow)
        self.label.setGeometry(QtCore.QRect(-40, 0, 191, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Main/Main/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(AdminWindow)
        self.frame.setGeometry(QtCore.QRect(100, 20, 451, 94))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.Admin_LEusername = QtWidgets.QLineEdit(self.frame)
        self.Admin_LEusername.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Admin_LEusername.setObjectName("Admin_LEusername")
        self.horizontalLayout.addWidget(self.Admin_LEusername)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Rshow = QtWidgets.QRadioButton(self.frame)
        self.Rshow.setObjectName("Rshow")
        self.horizontalLayout_2.addWidget(self.Rshow)
        self.Delshow = QtWidgets.QRadioButton(self.frame)
        self.Delshow.setObjectName("Delshow")
        self.horizontalLayout_2.addWidget(self.Delshow)
        self.Aenter = QtWidgets.QPushButton(self.frame)
        self.Aenter.setObjectName("Aenter")
        self.horizontalLayout_2.addWidget(self.Aenter)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.AdminDNE = QtWidgets.QLabel(AdminWindow)
        self.AdminDNE.setGeometry(QtCore.QRect(220, 110, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.AdminDNE.setFont(font)
        self.AdminDNE.setStyleSheet("color:rgb(255, 0, 0)")
        self.AdminDNE.setText("")
        self.AdminDNE.setAlignment(QtCore.Qt.AlignCenter)
        self.AdminDNE.setObjectName("AdminDNE")
        self.frame_2 = QtWidgets.QFrame(AdminWindow)
        self.frame_2.setGeometry(QtCore.QRect(20, 150, 531, 146))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 10, 421, 126))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ALfullname = QtWidgets.QLabel(self.layoutWidget)
        self.ALfullname.setText("")
        self.ALfullname.setAlignment(QtCore.Qt.AlignCenter)
        self.ALfullname.setObjectName("ALfullname")
        self.verticalLayout_2.addWidget(self.ALfullname)
        self.ALcontact = QtWidgets.QLabel(self.layoutWidget)
        self.ALcontact.setText("")
        self.ALcontact.setAlignment(QtCore.Qt.AlignCenter)
        self.ALcontact.setObjectName("ALcontact")
        self.verticalLayout_2.addWidget(self.ALcontact)
        self.ALemail = QtWidgets.QLabel(self.layoutWidget)
        self.ALemail.setText("")
        self.ALemail.setAlignment(QtCore.Qt.AlignCenter)
        self.ALemail.setObjectName("ALemail")
        self.verticalLayout_2.addWidget(self.ALemail)
        self.ALuser = QtWidgets.QLabel(self.layoutWidget)
        self.ALuser.setText("")
        self.ALuser.setAlignment(QtCore.Qt.AlignCenter)
        self.ALuser.setObjectName("ALuser")
        self.verticalLayout_2.addWidget(self.ALuser)
        self.ALpassw = QtWidgets.QLabel(self.layoutWidget)
        self.ALpassw.setText("")
        self.ALpassw.setAlignment(QtCore.Qt.AlignCenter)
        self.ALpassw.setObjectName("ALpassw")
        self.verticalLayout_2.addWidget(self.ALpassw)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 77, 126))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.ShowList = QtWidgets.QPushButton(AdminWindow)
        self.ShowList.setGeometry(QtCore.QRect(100, 120, 111, 21))
        self.ShowList.setObjectName("ShowList")
        self.Logout = QtWidgets.QPushButton(AdminWindow)
        self.Logout.setGeometry(QtCore.QRect(420, 300, 131, 41))
        self.Logout.setObjectName("Logout")

        self.retranslateUi(AdminWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "Admin"))
        self.label_2.setText(_translate("AdminWindow", "Enter the Username of Costumer: "))
        self.Rshow.setText(_translate("AdminWindow", "Show Info"))
        self.Delshow.setText(_translate("AdminWindow", "Delete Account"))
        self.Aenter.setText(_translate("AdminWindow", "Enter"))
        self.label_4.setText(_translate("AdminWindow", "Fullname:"))
        self.label_5.setText(_translate("AdminWindow", "Contact no."))
        self.label_6.setText(_translate("AdminWindow", "Email:"))
        self.label_7.setText(_translate("AdminWindow", "Username:"))
        self.label_8.setText(_translate("AdminWindow", "Password: "))
        self.ShowList.setText(_translate("AdminWindow", "Show List"))
        self.Logout.setText(_translate("AdminWindow", "Logout"))

import MainPics

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminWindow = QtWidgets.QWidget()
    ui = Ui_AdminWindow()
    ui.setupUi(AdminWindow)
    AdminWindow.show()
    sys.exit(app.exec_())

