# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Condo2Ui(object):
    def setupUi(self, Condo2Ui):
        Condo2Ui.setObjectName("Condo2Ui")
        Condo2Ui.resize(950, 542)
        Condo2Ui.setMinimumSize(QtCore.QSize(950, 542))
        Condo2Ui.setMaximumSize(QtCore.QSize(950, 542))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main/Main/Toma4025-Tea-Tea-plant-leaf.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Condo2Ui.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Condo2Ui)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(9, 9, 931, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.C2Tab1 = QtWidgets.QWidget()
        self.C2Tab1.setObjectName("C2Tab1")
        self.textBrowser = QtWidgets.QTextBrowser(self.C2Tab1)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 491, 451))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox = QtWidgets.QGroupBox(self.C2Tab1)
        self.groupBox.setGeometry(QtCore.QRect(500, -10, 421, 451))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.stackedWidget = QtWidgets.QStackedWidget(self.groupBox)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.stackedWidget.addWidget(self.page_12)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_8 = QtWidgets.QLabel(self.page_5)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/Condo2/Condo2/10.jpeg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Condo2/Condo2/1.jpeg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_6 = QtWidgets.QLabel(self.page_6)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/Condo2/Condo2/11.jpeg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Condo2/Condo2/2.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Condo2/Condo2/3.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Condo2/Condo2/4.jpeg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_9 = QtWidgets.QLabel(self.page_7)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/Condo2/Condo2/5.jpeg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_10 = QtWidgets.QLabel(self.page_8)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/Condo2/Condo2/6.jpeg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_11.addWidget(self.label_10, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_9)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_11 = QtWidgets.QLabel(self.page_9)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/Condo2/Condo2/7.jpeg"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.gridLayout_12.addWidget(self.label_11, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_10)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_12 = QtWidgets.QLabel(self.page_10)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/Condo2/Condo2/8.jpeg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout_13.addWidget(self.label_12, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_10)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_11)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_13 = QtWidgets.QLabel(self.page_11)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/Condo2/Condo2/9.jpeg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_14.addWidget(self.label_13, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_11)
        self.gridLayout_8.addWidget(self.stackedWidget, 2, 0, 1, 1)
        self.C2spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.C2spinBox.setReadOnly(False)
        self.C2spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.C2spinBox.setKeyboardTracking(False)
        self.C2spinBox.setMinimum(1)
        self.C2spinBox.setMaximum(11)
        self.C2spinBox.setObjectName("C2spinBox")
        self.gridLayout_8.addWidget(self.C2spinBox, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.C2Buy = QtWidgets.QPushButton(self.groupBox)
        self.C2Buy.setObjectName("C2Buy")
        self.horizontalLayout.addWidget(self.C2Buy)
        self.C2Cancel = QtWidgets.QPushButton(self.groupBox)
        self.C2Cancel.setObjectName("C2Cancel")
        self.horizontalLayout.addWidget(self.C2Cancel)
        self.gridLayout_8.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 0, 0, 1, 1)
        self.groupBox.raise_()
        self.textBrowser.raise_()
        self.tabWidget.addTab(self.C2Tab1, "")
        self.C2Tab2 = QtWidgets.QWidget()
        self.C2Tab2.setObjectName("C2Tab2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.C2Tab2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_7 = QtWidgets.QLabel(self.C2Tab2)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/Condo2/Condo2/map2.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.C2Tab2, "")
        Condo2Ui.setCentralWidget(self.centralwidget)

        self.retranslateUi(Condo2Ui)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        self.C2spinBox.valueChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Condo2Ui)

    def retranslateUi(self, Condo2Ui):
        _translate = QtCore.QCoreApplication.translate
        Condo2Ui.setWindowTitle(_translate("Condo2Ui", "Condo 2 Details"))
        self.textBrowser.setHtml(_translate("Condo2Ui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:12pt; font-weight:600;\">Price: P1,250,190/$28,754</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-weight:600;\">1 bedrooms</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-weight:600;\">1 bathrooms</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-weight:600;\">25 m</span><span style=\" font-family:\'Sans Serif\'; font-weight:600; vertical-align:super;\">2</span><span style=\" font-family:\'Sans Serif\'; font-weight:600;\"> floor area</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:600; font-style:italic;\">Urban Deca Homes Marilao</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt; font-style:italic;\">Born out of the commitment to meet a serious housing shortage in the country.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:600; text-decoration: underline;\">Details</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">   </span><span style=\" font-family:\'Sans Serif\'; font-size:9pt; font-style:italic;\"> Alarm System</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt; font-style:italic;\">    Smoke detector</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt; font-style:italic;\">    Elevators</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt; font-style:italic;\">    Fire exits</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt; font-style:italic;\">    Fire Alarm</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt; font-style:italic;\">    24-hour security</span></p></body></html>"))
        self.C2Buy.setText(_translate("Condo2Ui", "BUY"))
        self.C2Cancel.setText(_translate("Condo2Ui", "CANCEL"))
        self.label_5.setText(_translate("Condo2Ui", "See Photos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.C2Tab1), _translate("Condo2Ui", "House Details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.C2Tab2), _translate("Condo2Ui", "Location"))

import HousePlan
import MainPics

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Condo2Ui = QtWidgets.QMainWindow()
    ui = Ui_Condo2Ui()
    ui.setupUi(Condo2Ui)
    Condo2Ui.show()
    sys.exit(app.exec_())

