# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H3.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_House3Ui(object):
    def setupUi(self, House3Ui):
        House3Ui.setObjectName("House3Ui")
        House3Ui.resize(758, 542)
        House3Ui.setMinimumSize(QtCore.QSize(758, 542))
        House3Ui.setMaximumSize(QtCore.QSize(758, 542))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main/Main/Toma4025-Tea-Tea-plant-leaf.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        House3Ui.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(House3Ui)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(9, 9, 741, 524))
        self.tabWidget.setObjectName("tabWidget")
        self.H3Tab1 = QtWidgets.QWidget()
        self.H3Tab1.setObjectName("H3Tab1")
        self.groupBox = QtWidgets.QGroupBox(self.H3Tab1)
        self.groupBox.setGeometry(QtCore.QRect(260, -10, 471, 491))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.stackedWidget = QtWidgets.QStackedWidget(self.groupBox)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.stackedWidget.addWidget(self.page_13)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/House3/House 3/1.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/House3/House 3/11.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_8 = QtWidgets.QLabel(self.page_5)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/House3/House 3/12.jpeg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/House3/House 3/13.jpeg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_6 = QtWidgets.QLabel(self.page_6)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/House3/House 3/2.jpeg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_9 = QtWidgets.QLabel(self.page_7)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/House3/House 3/3.jpeg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_11.addWidget(self.label_9, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_10 = QtWidgets.QLabel(self.page_8)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/House3/House 3/4.jpeg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_12.addWidget(self.label_10, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_9)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_11 = QtWidgets.QLabel(self.page_9)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/House3/House 3/5.jpeg"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.gridLayout_13.addWidget(self.label_11, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_10)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_12 = QtWidgets.QLabel(self.page_10)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/House3/House 3/6.jpeg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout_14.addWidget(self.label_12, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_10)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_11)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_13 = QtWidgets.QLabel(self.page_11)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/House3/House 3/7.jpeg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_15.addWidget(self.label_13, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_11)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.page_12)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_14 = QtWidgets.QLabel(self.page_12)
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/House3/House 3/8.jpeg"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout_16.addWidget(self.label_14, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_12)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/House3/House 3/10.jpeg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_8.addWidget(self.stackedWidget, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.H3Buy = QtWidgets.QPushButton(self.groupBox)
        self.H3Buy.setObjectName("H3Buy")
        self.horizontalLayout.addWidget(self.H3Buy)
        self.H3Cancel = QtWidgets.QPushButton(self.groupBox)
        self.H3Cancel.setObjectName("H3Cancel")
        self.horizontalLayout.addWidget(self.H3Cancel)
        self.gridLayout_8.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(12)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_8.addWidget(self.spinBox, 1, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.H3Tab1)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 251, 451))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.H3Tab1, "")
        self.H3Tab2 = QtWidgets.QWidget()
        self.H3Tab2.setObjectName("H3Tab2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.H3Tab2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_7 = QtWidgets.QLabel(self.H3Tab2)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/House3/House 3/map.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.H3Tab2, "")
        House3Ui.setCentralWidget(self.centralwidget)

        self.retranslateUi(House3Ui)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        self.spinBox.valueChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(House3Ui)

    def retranslateUi(self, House3Ui):
        _translate = QtCore.QCoreApplication.translate
        House3Ui.setWindowTitle(_translate("House3Ui", "House 3 Details"))
        self.label_5.setText(_translate("House3Ui", "See Photos"))
        self.H3Buy.setText(_translate("House3Ui", "BUY"))
        self.H3Cancel.setText(_translate("House3Ui", "CANCEL"))
        self.textBrowser.setHtml(_translate("House3Ui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Price: P48,000,000/$1,104,000</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; font-style:italic;\">8 bedrooms</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; font-style:italic;\">625 m</span><span style=\" font-size:12pt; font-weight:600; font-style:italic; vertical-align:super;\">2</span><span style=\" font-size:12pt; font-weight:600; font-style:italic;\"> Floor area</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; font-style:italic;\">835 m</span><span style=\" font-size:12pt; font-weight:600; font-style:italic; vertical-align:super;\">2</span><span style=\" font-size:12pt; font-weight:600; font-style:italic;\"> Land Size</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">House and Lot for Sale in an exclusive subdivision</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">House and Lot for Sale, Pristina North Subdivision, Talamban, Cebu City</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.H3Tab1), _translate("House3Ui", "House Details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.H3Tab2), _translate("House3Ui", "Location"))

import HousePlan
import MainPics

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    House3Ui = QtWidgets.QMainWindow()
    ui = Ui_House3Ui()
    ui.setupUi(House3Ui)
    House3Ui.show()
    sys.exit(app.exec_())

