# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignUp.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SignUpWindow(object):
    

    def setupUi(self, SignUpWindow):
        SignUpWindow.setObjectName("SignUpWindow")
        SignUpWindow.resize(642, 519)
        SignUpWindow.setMinimumSize(QtCore.QSize(642,519))
        SignUpWindow.setMaximumSize(QtCore.QSize(642,519))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main/Main/Toma4025-Tea-Tea-plant-leaf.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SignUpWindow.setWindowIcon(icon)
        self.label_6 = QtWidgets.QLabel(SignUpWindow)
        self.label_6.setGeometry(QtCore.QRect(-30, 70, 281, 211))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/Main/Main/logo.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.frame = QtWidgets.QFrame(SignUpWindow)
        self.frame.setGeometry(QtCore.QRect(220, 10, 401, 301))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(140, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 70, 341, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.SLE_Fullname = QtWidgets.QLineEdit(self.layoutWidget)
        self.SLE_Fullname.setMaxLength(50)
        self.SLE_Fullname.setObjectName("SLE_Fullname")
        self.verticalLayout.addWidget(self.SLE_Fullname)
        self.SLE_Phone = QtWidgets.QLineEdit(self.layoutWidget)
        self.SLE_Phone.setMaxLength(16)
        self.SLE_Phone.setObjectName("SLE_Phone")
        self.verticalLayout.addWidget(self.SLE_Phone)
        self.SLE_Email = QtWidgets.QLineEdit(self.layoutWidget)
        self.SLE_Email.setMaxLength(30)
        self.SLE_Email.setObjectName("SLE_Email")
        self.verticalLayout.addWidget(self.SLE_Email)
        self.SLE_Username = QtWidgets.QLineEdit(self.layoutWidget)
        self.SLE_Username.setMaxLength(20)
        self.SLE_Username.setObjectName("SLE_Username")
        self.verticalLayout.addWidget(self.SLE_Username)
        self.SLE_Password = QtWidgets.QLineEdit(self.layoutWidget)
        self.SLE_Password.setMaxLength(20)
        self.SLE_Password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.SLE_Password.setObjectName("SLE_Password")
        self.verticalLayout.addWidget(self.SLE_Password)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.frame_2 = QtWidgets.QFrame(SignUpWindow)
        self.frame_2.setGeometry(QtCore.QRect(20, 410, 601, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 171, 41))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/Main/Main/Lamundi.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(270, 10, 71, 71))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/Main/Main/MapuaLogo.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(370, -30, 201, 141))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/Main/Main/Sponsor.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.layoutWidget1 = QtWidgets.QWidget(SignUpWindow)
        self.layoutWidget1.setGeometry(QtCore.QRect(320, 360, 231, 34))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SPB_Signup = QtWidgets.QPushButton(self.layoutWidget1)
        self.SPB_Signup.setObjectName("SPB_Signup")
        self.horizontalLayout_2.addWidget(self.SPB_Signup)
        self.SPB_cancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.SPB_cancel.setObjectName("SPB_cancel")
        self.horizontalLayout_2.addWidget(self.SPB_cancel)
        self.SignUpLabel = QtWidgets.QLabel(SignUpWindow)
        self.SignUpLabel.setGeometry(QtCore.QRect(280, 310, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.SignUpLabel.setFont(font)
        self.SignUpLabel.setStyleSheet("color:rgb(255, 0, 0)")
        self.SignUpLabel.setText("")
        self.SignUpLabel.setScaledContents(False)
        self.SignUpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SignUpLabel.setObjectName("SignUpLabel")
        self.layoutWidget.raise_()
        self.label_6.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.SignUpLabel.raise_()

        self.retranslateUi(SignUpWindow)
        QtCore.QMetaObject.connectSlotsByName(SignUpWindow)

    def retranslateUi(self, SignUpWindow):
        _translate = QtCore.QCoreApplication.translate
        SignUpWindow.setWindowTitle(_translate("SignUpWindow", "Sign Up"))
        self.label_7.setText(_translate("SignUpWindow", "Register"))
        self.label_2.setText(_translate("SignUpWindow", "Full name:"))
        self.label_5.setText(_translate("SignUpWindow", "Phone number:"))
        self.label_4.setText(_translate("SignUpWindow", "Email:"))
        self.label.setText(_translate("SignUpWindow", "Username:"))
        self.label_3.setText(_translate("SignUpWindow", "Password:"))
        self.label_11.setText(_translate("SignUpWindow", "In Partnership with"))
        self.SPB_Signup.setText(_translate("SignUpWindow", "Sign Up"))
        self.SPB_cancel.setText(_translate("SignUpWindow", "Cancel"))

import MainPics

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignUpWindow = QtWidgets.QWidget()
    ui = Ui_SignUpWindow()
    ui.setupUi(SignUpWindow)
    SignUpWindow.show()
    sys.exit(app.exec_())

